### ISSUE TITLE
"Play" site shows local timezone, while it should probably show UTC-4

### ISSUE THREAD

**Issue by hajducsekb** [Re-Volt-America/Website#6]
I'm pretty sure the goal of this clock is for people to find out what the current time in UTC-4 is. Well, it doesn't do that. :)
This might be helpful, but I don't know js: https://stackoverflow.com/questions/7947975/id-like-to-create-a-javascript-clock-for-a-specific-time-zone.

**Comment by BGMP** [comment]
Thanks, I will look into it. I only had people from timezones similar to mine looking at the website whilst it was indev, so this was kind of difficult to figure out, since at first we thought it had to do with our timezones being just 1 hour apart.

And yeah, don't blame you, I just used javascript because I had to.
